__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

а) $A \cdot B$ и $B \cdot A$ не определены;

б) $A \cdot B$ определено, $AB$ — матрица $2\times 3$, $B \cdot A$ не определено;

в) $A \cdot B$ определено, $AB$ — матрица $8\times 8$, $B \cdot A$ определено, $BA$ — матрица $3\times 3$;

г) $A \cdot B$ и $B \cdot A$ определены, $AB$ и $BA$ — квадратные матрицы $4\times 4$.

In [9]:
import numpy as np

In [7]:
a = np.ones((4,2))
b = np.ones((2,5))
c = np.ones((5,3))
d = np.ones((8,3))
e = np.ones((3,8))
f = np.ones((4,4))

print(np.shape(np.dot(b,c)))
print(np.shape(np.dot(d,e)))
print(np.shape(np.dot(e,d)))
print(np.shape(np.dot(f,f)))

(2, 3)
(8, 8)
(3, 3)
(4, 4)


__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$$A+B = \begin{pmatrix}
1 & -2\\ 
3 & 0 
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\
3 & 5
\end{pmatrix}
$$

$$A\cdot B = \begin{pmatrix}
1\cdot4+(-2)\cdot0 & 1\cdot(-1)+(-2)\cdot5\\
3\cdot4+0\cdot0 & 3\cdot(-1)+0\cdot5
\end{pmatrix} = \begin{pmatrix}
4 & -11\\
12 & -3
\end{pmatrix}
$$

$$B\cdot A = \begin{pmatrix}
4\cdot1+(-1)\cdot3 & 4\cdot(-2)+(-1)\cdot0\\
0\cdot1+5\cdot3 & 0\cdot(-2)+5\cdot0
\end{pmatrix} = \begin{pmatrix}
1 & -8\\
15 & 0
\end{pmatrix}
$$

In [12]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'A + B =\n{A + B}')
print(f'AB =\n{np.dot(A, B)}')
print(f'BA =\n{np.dot(B, A)}')

A + B =
[[ 5 -3]
 [ 3  5]]
AB =
[[  4 -11]
 [ 12  -3]]
BA =
[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$$3A-2B+4C = 3\cdot\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2\cdot\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 4\cdot\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
3\cdot1+0+4\cdot2 & 3\cdot7-2\cdot5-4\cdot4\\ 
3\cdot3-2\cdot2+4\cdot1 & -3\cdot6+2\cdot1+4\cdot1
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}
$$

In [13]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'3A - 2B + 4C =\n{3 * A - 2 * B + 4 * C}')

3A - 2B + 4C =
[[ 11  -5]
 [  9 -12]]


__4*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [33]:
class Matrix:
    
    def __init__(self, matrix):
        self.matrix = matrix
        
    def __str__(self):
        return '[' + '\n '.join(['\t'.join([str(i) for i in el]) for el in self.matrix]) + ']'
    
    def __mul__(self, other):
        if len(self.matrix[0]) != len(other.matrix):
            return "Matrix multiplication is not defined."
        else:
            result = []
            row = []
            for i in range(len(self.matrix)):
                for j in range(len(other.matrix[0])):
                    row.append(sum([self.matrix[i][p] * other.matrix[p][j] for p in range(len(self.matrix[0]))]))
                    if len(row) == len(other.matrix[0]):
                        result.append(row)
                        row = []
            result = Matrix(result)
            return result


A = Matrix([[1, -2], [3, 0]])
B = Matrix([[4, -1], [0, 5]])

print(A * B)
print(B * A)

C = Matrix([[2, 2, -1], [0, 3, 5]])

print(A * C)
print(C * A)

D = Matrix([[2],[3]])

print(A * D)
print(D * A)


[4	-11
 12	-3]
[1	-8
 15	0]
[2	-4	-11
 6	6	-3]
Matrix multiplication is not defined.
[-4
 6]
Matrix multiplication is not defined.
