__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

a) $$\begin{vmatrix}
\sin x & -\cos x\\ 
\cos x & \sin x
\end{vmatrix} = \sin x \cdot \sin x - (-\cos x) \cdot \cos x = \sin^2 x + \cos^2 x = 1$$

б) $$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4\begin{vmatrix}
5 & 1\\ 
0 & 9
\end{vmatrix} - 2\begin{vmatrix}
0 & 1\\ 
0 & 9
\end{vmatrix} + 3\begin{vmatrix}
0 & 5\\ 
0 & 0
\end{vmatrix} = 4\cdot45 - 2\cdot0 + 3\cdot0 = 180$$

в) Заметим, что третья строка матрицы является линейной комбинацией первых двух, а именно $a_{3j} = 2a_{2j}-a_{1j}$. Поэтому

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 0$$

In [1]:
import numpy as np

In [6]:
a = np.array([[np.sin(0.5), -np.cos(0.5)], [np.cos(0.5), np.sin(0.5)]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ 0.47942554 -0.87758256]
 [ 0.87758256  0.47942554]]
Определитель:
1


In [7]:
b = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{b}')
print(f'Определитель:\n{np.linalg.det(b):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


In [8]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{c}')
print(f'Определитель:\n{np.linalg.det(c):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а) $det(A^{2}) = det(A\cdot A) = detA \cdot detA = 4\cdot4 = 16$

б) $det(A^{T}) = detA = 4$

в) $det(2A) = 2^n \cdot detA = 2^n\cdot4$, где $n$ - порядок матрицы $A$.

In [14]:
A = np.array([[2, -1], [0, 2]])
print(f'Матрица:\n{A}')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

A_2 = np.dot(A, A)
print(f'Матрица:\n{A_2}')
print(f'Определитель:\n{np.linalg.det(A_2):.0f}')

AT = A.T
print(f'Матрица:\n{AT}')
print(f'Определитель:\n{np.linalg.det(AT):.0f}')

A2 = 2 * A
print(f'Матрица:\n{A2}')
print(f'Определитель:\n{np.linalg.det(A2):.0f}')

A = np.array([[2, -1, 0], [0, 2, 1], [0, 0, 1]])
print(f'Матрица:\n{A}')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

A2 = 2 * A
print(f'Матрица:\n{A2}')
print(f'Определитель:\n{np.linalg.det(A2):.0f}')

Матрица:
[[ 2 -1]
 [ 0  2]]
Определитель:
4
Матрица:
[[ 4 -4]
 [ 0  4]]
Определитель:
16
Матрица:
[[ 2  0]
 [-1  2]]
Определитель:
4
Матрица:
[[ 4 -2]
 [ 0  4]]
Определитель:
16
Матрица:
[[ 2 -1  0]
 [ 0  2  1]
 [ 0  0  1]]
Определитель:
4
Матрица:
[[ 4 -2  0]
 [ 0  4  2]
 [ 0  0  2]]
Определитель:
32


__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

$$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix} = -2\cdot\begin{vmatrix}
-2 & 7 & -3\\ 
-2 & 7 & -3\\ 
-3 & 7 & 13
\end{vmatrix} = -2\cdot0 = 0$$

Так как определитель матрицы, у которой две строки равны между собой, равен $0$.

In [15]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{A}')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

а) Третья строка является суммой первой и второй строк, значит ее можно отбросить:

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1 
\end{pmatrix}$

Вычтем из второй строки первую:

$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2 
\end{pmatrix}$

Таким образом, ранг матрицы равен $2$.

б) Третья строка является суммой первой и второй строк, значит ее можно отбросить:

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

Второй столбец является произведением первого столбца на $1.5$, значит его можно отбросить:

$\begin{pmatrix}
0 & 2 & 1\\ 
0 & 2 & 2\\ 
2 & 5 & 6
\end{pmatrix}$

Переставим третью и первую строки:

$\begin{pmatrix}
2 & 5 & 6\\ 
0 & 2 & 2\\ 
0 & 2 & 1
\end{pmatrix}$

Вычтем из третьей строки вторую:

$\begin{pmatrix}
2 & 5 & 6\\ 
0 & 2 & 2\\ 
0 & 0 & -1
\end{pmatrix}$

Таким образом, ранг матрицы равен $3$.

In [16]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(a)

print(f'Матрица:\n{a}')
print(f'Ранг матрицы: {r}')

b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
r = np.linalg.matrix_rank(b)

print(f'Матрица:\n{b}')
print(f'Ранг матрицы: {r}')

Матрица:
[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг матрицы: 2
Матрица:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Ранг матрицы: 3
