__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

Составим и решим характеристическое уравнение:

$$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0$$

$$(-1-\lambda)(6-\lambda)-2\cdot(-6)=0$$

$$-6-6\lambda+\lambda+\lambda^{2}+12=0$$

$$\lambda^{2}-5\lambda+6=0$$

$$(\lambda-2)(\lambda-3)=0$$

$$\lambda_{1}=2, \lambda_{2}=3$$

Теперь найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученные собственные значения в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$$

$$\lambda_{1}=2:$$

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
2\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$$

$$\begin{cases}
-x_{1}-6x_{2} = 2x_{1}, \\
2x_{1}+6x_{2} = 2x_{2}
\end{cases}$$

$$\begin{cases}
-3x_{1}=6x_{2}, \\
2x_{1}=-4x_{2}
\end{cases}$$

$$\begin{cases}
x_{1}=-2x_{2}, \\
x_{1}=-2x_{2}
\end{cases}$$

Таким образом, собственными векторами является бесконечное множество векторов вида $\begin{pmatrix}
-2x_{2}\\ 
x_{2}
\end{pmatrix}$, например $\begin{pmatrix}
-2\\ 
1
\end{pmatrix}$.

$$\lambda_{2}=3:$$

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
3\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$$

$$\begin{cases}
-x_{1}-6x_{2} = 3x_{1}, \\
2x_{1}+6x_{2} = 3x_{2}
\end{cases}$$

$$\begin{cases}
-4x_{1}=6x_{2}, \\
2x_{1}=-3x_{2}
\end{cases}$$

$$\begin{cases}
2x_{1}=-3x_{2}, \\
2x_{1}=-3x_{2}
\end{cases}$$

Таким образом, собственными векторами является бесконечное множество векторов вида $\begin{pmatrix}
-\frac{3}{2}x_{2}\\ 
x_{2}
\end{pmatrix}$, например $\begin{pmatrix}
-3\\ 
2
\end{pmatrix}$.

In [3]:
import numpy as np

In [5]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

Составим и решим характеристическое уравнение:

$$\begin{vmatrix}
-1-\lambda & 0\\ 
0 & -1-\lambda
\end{vmatrix} = 0$$

$$(-1-\lambda)(-1-\lambda)=0$$

$$(-1-\lambda)^{2}=0$$

$$-1-\lambda=0$$

$$\lambda_{1}=\lambda_{2}=-1$$

Теперь найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученные собственные значения в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
-1\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$$

$$\begin{cases}
-x_{1} = -x_{1}, \\
-x_{2} = -x_{2}
\end{cases}$$

Отсюда следует, что за обе координаты можно принять любое значение, то есть любой вектор является собственным для линейного оператора $A$ с собственным значением $\lambda=-1$.

In [8]:
a = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора $A$, тогда должно существовать некоторое вещественное число $\lambda$, при котором 

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1 
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}
$$

Следовательно,

$$\begin{cases}
1+1 = 1\cdot\lambda \\ 
-1+3 = 1\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}$$

Таким образом, вектор $x=(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$, и его собственное значение составляет $\lambda=2$.

In [6]:
a = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2. 2.]
Собственные векторы:
[[ 0.71 -0.71]
 [ 0.71 -0.71]]


__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора $A$, тогда должно существовать некоторое вещественное число $\lambda$, при котором 

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4 
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}
$$

Следовательно,

$$\begin{cases}
3\cdot(-3) = 3\cdot\lambda \\ 
3\cdot3 = -3\cdot\lambda
3\cdot(-4) = -4\cdot\lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=-3\\ 
\lambda=-3\\
\lambda=3
\end{cases}$$

Такая система не имеет смысла, следовательно, вектор $x=(3,-3,-4)$ не является собственным вектором линейного оператора, заданного матрицей $A$.

In [7]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.71 -0.71  0.  ]
 [ 0.71  0.71  0.  ]
 [ 0.    0.    1.  ]]
