__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

Запишем расширенную матрицу системы:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\
2 & 1 & -1 & 1\\
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

Путем элементарных преобразований приведем матрицу к ступенчатому виду.

Из второй строки вычтем первую, умноженную на $2$, и из третьей вычтем первую.

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\
0 & -1 & 1 & 5\\
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

Полученная матрица соответствует системе:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
~~-x_{2}+x_{3}+5x_{4}=-2, \\
~~~~-2x_{3}+3x_{4}=4
\end{cases}$$

Запишем общее решение системы. Пусть $x_{4}=c$. Тогда, выражая остальные переменные через $c$, получим:

$$x_{4}=c,$$
$$-2x_{3}+3c=4 \; \Leftrightarrow \; x_{3}=1.5c-2,$$
$$-x_{2}+1.5c-2+5c=-2 \; \Leftrightarrow \; x_{2}=6.5c,$$
$$x_{1}+6.5c-1.5c+2-2c=0 \; \Leftrightarrow \; x_{1}=-3c-2.$$

Например, при $c=0$:

$$x_{1}=-2,$$
$$x_{2}=0,$$
$$x_{3}=-2,$$
$$x_{4}=0.$$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [1]:
import numpy as np

In [8]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
r = np.linalg.matrix_rank(A)

print(f'Матрица:\n{A}')
print(f'Ранг матрицы: {r}')

A_ = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])
r = np.linalg.matrix_rank(A_)

print(f'Матрица:\n{A_}')
print(f'Ранг матрицы: {r}')

Матрица:
[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]
Ранг матрицы: 3
Матрица:
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]
Ранг матрицы: 3


а) По теореме Кронекера-Капелли, т.к. $rankA=rank \tilde A=3$ и $n=3$ — число неизвестных, система совместна и имеет единственное решение.

In [9]:
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
r = np.linalg.matrix_rank(A)

print(f'Матрица:\n{A}')
print(f'Ранг матрицы: {r}')

A_ = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])
r = np.linalg.matrix_rank(A_)

print(f'Матрица:\n{A_}')
print(f'Ранг матрицы: {r}')

Матрица:
[[ 2 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]
Ранг матрицы: 1
Матрица:
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]
Ранг матрицы: 2


б) По теореме Кронекера-Капелли, т.к. $rankA<rank \tilde A$, система несовместна.

In [10]:
A = np.array([[1, 2, 5], [3, 1, -8]])
r = np.linalg.matrix_rank(A)

print(f'Матрица:\n{A}')
print(f'Ранг матрицы: {r}')

A_ = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])
r = np.linalg.matrix_rank(A_)

print(f'Матрица:\n{A_}')
print(f'Ранг матрицы: {r}')

Матрица:
[[ 1  2  5]
 [ 3  1 -8]]
Ранг матрицы: 2
Матрица:
[[ 1  2  5  4]
 [ 3  1 -8 -2]]
Ранг матрицы: 2


в) По теореме Кронекера-Капелли, т.к. $rankA=rank \tilde A=2<3$ и $n=3$ — число неизвестных, система совместна и имеет бесконечное количество решений.

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [11]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
r = np.linalg.matrix_rank(A)

print(f'Матрица:\n{A}')
print(f'Ранг матрицы: {r}')

A_ = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])
r = np.linalg.matrix_rank(A_)

print(f'Матрица:\n{A_}')
print(f'Ранг матрицы: {r}')

Матрица:
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]
Ранг матрицы: 4
Матрица:
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]
Ранг матрицы: 4


По теореме Кронекера-Капелли, т.к. $rankA=rank \tilde A=4$ и $n=4$ — число неизвестных, система совместна и имеет единственное решение.

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

In [12]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
r = np.linalg.matrix_rank(A)

print(f'Матрица:\n{A}')
print(f'Ранг матрицы: {r}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Ранг матрицы: 2


По теореме Кронекера-Капелли система будет совместной тогда и только тогда когда $rankA=rank \tilde A$.

Так как $rankA=2<3$, одна из строк (или столбцов) матрицы $A$ является линейно зависимой. Заметим, что третья строка представляет собой линейную комбинацию первой и второй строк, а именно:

$$(3) = 2\cdot(2)-(1)$$

Для того чтобы ранг расширенной матрицы оставался равным $2$, нужно чтобы последний элемент $c$ тоже был соответствующей линейной комбинацией $a$ и $b$.

То есть система совместна тогда и только тогда когда $c = 2b-a$.

Соответственно, система несовместна когда $c \ne 2b-a$.

In [14]:
A_= np.array([[1, 2, 3, 1], [4, 5, 6, 3], [7, 8, 9, 5]])
r = np.linalg.matrix_rank(A_)

print(f'Матрица:\n{A_}')
print(f'Ранг матрицы: {r}')

A_= np.array([[1, 2, 3, 0], [4, 5, 6, 7], [7, 8, 9, 3]])
r = np.linalg.matrix_rank(A_)

print(f'Матрица:\n{A_}')
print(f'Ранг матрицы: {r}')

Матрица:
[[1 2 3 1]
 [4 5 6 3]
 [7 8 9 5]]
Ранг матрицы: 2
Матрица:
[[1 2 3 0]
 [4 5 6 7]
 [7 8 9 3]]
Ранг матрицы: 3
