__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

а) Найдем определитель матрицы коэффициентов:

$$detA=\begin{vmatrix}
1 & -2\\ 
3 & -4
\end{vmatrix}=1\cdot(-4)+2\cdot3=-4+6=2\neq 0,$$

следовательно, система совместна.

Найдем определители $detA_{1}$ и $detA_{2}$:

$$detA_{1}=\begin{vmatrix}
1 & -2\\ 
7 & -4
\end{vmatrix}=1\cdot(-4)+2\cdot7=-4+14=10,$$

$$detA_{2}=\begin{vmatrix}
1 & 1\\ 
3 & 7
\end{vmatrix}=1\cdot7-1\cdot3=7-3=4.$$

Найдем решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5,$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2.$$

б) Найдем определитель матрицы коэффициентов:

$$detA=\begin{vmatrix}
2 & -1 & 5\\ 
1 & 1 & -3\\ 
2 & 4 & 1
\end{vmatrix}=
2\begin{vmatrix}
1 & -3\\ 
4 & 1 
\end{vmatrix}+
\begin{vmatrix}
1 & -3\\ 
2 & 1 
\end{vmatrix}+
5\begin{vmatrix}
1 & 1 \\ 
2 & 4
\end{vmatrix}=2(1\cdot1+3\cdot4)+(1\cdot 1+3\cdot2)+5(1\cdot4-1\cdot2)=26+7+10=43\neq 0,$$

следовательно, система совместна.

Найдем определители $detA_{1}$, $detA_{2}$, $detA_{3}$:

$$detA_{1}=\begin{vmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3\\ 
1 & 4 & 1
\end{vmatrix}=
10\begin{vmatrix}
1 & -3\\ 
4 & 1 
\end{vmatrix}+
\begin{vmatrix}
-2 & -3\\ 
1 & 1 
\end{vmatrix}+
5\begin{vmatrix}
-2 & 1 \\ 
1 & 4
\end{vmatrix}=10(1\cdot1+3\cdot4)+(-2\cdot1+3\cdot1)+5(-2\cdot4-1\cdot1)=130+1-45=86,$$

$$detA_{2}=\begin{vmatrix}
2 & 10 & 5\\ 
1 & -2 & -3\\ 
2 & 1 & 1
\end{vmatrix}=
2\begin{vmatrix}
-2 & -3\\ 
1 & 1 
\end{vmatrix}-
10\begin{vmatrix}
1 & -3\\ 
2 & 1 
\end{vmatrix}+
5\begin{vmatrix}
1 & -2 \\ 
2 & 1
\end{vmatrix}=2(-2\cdot1+3\cdot1)-10(1\cdot 1+3\cdot2)+5(1\cdot1+2\cdot2)=2-70+25=-43,$$

$$detA_{3}=\begin{vmatrix}
2 & -1 & 10\\ 
1 & 1 & -2\\ 
2 & 4 & 1
\end{vmatrix}=
2\begin{vmatrix}
1 & -2\\ 
4 & 1 
\end{vmatrix}+
\begin{vmatrix}
1 & -2\\ 
2 & 1 
\end{vmatrix}+
10\begin{vmatrix}
1 & 1 \\ 
2 & 4
\end{vmatrix}=2(1\cdot1+2\cdot4)+(1\cdot1+2\cdot2)+10(1\cdot4-1\cdot2)=18+5+20=43.$$

Найдем решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2,$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43}=-1,$$

$$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1.$$

__2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

а) Домножим первую строку на $2$ и вычтем ее из второй строки. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $2$. Затем нам нужно вычесть из третьей строки первую, домноженную на $3$. Значит, в матрицу $L$ запишем $l_{31}=3$. 

Матрица коэффициентов будет иметь вид

$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4\\ 
0 & 20 & 18
\end{pmatrix},$$

а матрица $L$ —

$$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & l_{32} & 1
\end{pmatrix}.$$

Далее умножим вторую строку на $4$ и вычтем ее из третьей. При этом в матрицу $L$ на место $l_{32}$ запишем $4$.

В итоге получим

$$U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix},$$

$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}.$$

б) Домножим первую строку на $2$ и вычтем ее из второй строки. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $2$. Затем нам нужно вычесть из третьей строки первую, домноженную на $3$, а из четвертой строки - первую, домноженную на $4$. Значит, в матрицу $L$ запишем $l_{31}=3$ и $l_{41}=4$. 

Матрица коэффициентов будет иметь вид

$$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 15 & 23 & 6 \\
0 & 18 & 45 & 17
\end{pmatrix},$$

а матрица $L$ —

$$\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & l_{32} & 1 & 0 \\
4 & l_{42} & l_{43} & 1
\end{pmatrix}.$$

Далее умножим вторую строку на $5$ и вычтем ее из третьей. При этом в матрицу $L$ на место $l_{32}$ запишем $5$. Затем нам нужно вычесть из четвертой строки вторую, домноженную на $6$. Значит, в матрицу $L$ запишем $l_{42}=6$.

Матрица коэффициентов будет иметь вид

$$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 0 & 21 & 11
\end{pmatrix},$$

а матрица $L$ —

$$\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0 \\
4 & 6 & l_{43} & 1
\end{pmatrix}.$$

Далее умножим третью строку на $7$ и вычтем ее из четвертой. При этом в матрицу $L$ на место $l_{43}$ запишем $7$.

В итоге получим

$$U=\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 0 & 0 & 4
\end{pmatrix},$$

$$L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0 \\
4 & 6 & 7 & 1
\end{pmatrix}.$$

__3.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

Матрица коэффициентов имеет вид

$$\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5\\ 
9 & 8 & 4
\end{pmatrix}.$$

Домножим первую строку на $\frac{11}{2}$ и вычтем ее из второй строки. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $\frac{11}{2}$. Затем нам нужно вычесть из третьей строки первую, домноженную на $\frac{9}{2}$. Значит, в матрицу $L$ запишем $l_{31}=\frac{9}{2}$. 

Матрица коэффициентов будет иметь вид

$$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2}\\ 
0 & \frac{7}{2} & -\frac{19}{2}
\end{pmatrix},$$

а матрица $L$ —

$$\begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
\frac{9}{2} & l_{32} & 1
\end{pmatrix}.$$

Далее умножим вторую строку на $\frac{7}{3}$ и вычтем ее из третьей. При этом в матрицу $L$ на место $l_{32}$ запишем $\frac{7}{3}$.

В итоге получим

$$U=\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2}\\ 
0 & 0 & \frac{52}{3}
\end{pmatrix},$$

$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
\frac{9}{2} & \frac{7}{3} & 1
\end{pmatrix}.$$

Решим теперь систему 

$$Ly=b:$$

$$\begin{cases}
y_{1}=1, \\
\frac{11}{2}y_{1}+y_{2}=-6, \\
\frac{9}{2}y_{1}+\frac{7}{3}y_{2}+y_{3}=-5.
\end{cases}$$

$$y_{1}=1,$$
$$y_{2}=-\frac{23}{2},$$
$$y_{3}=\frac{52}{3}.$$

И затем систему

$$Ux=y:$$

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1, \\
\frac{3}{2}x_{2}-\frac{23}{2}x_{3}=-\frac{23}{2}, \\
\frac{52}{3}x_{3}=\frac{52}{3}.
\end{cases}$$

$$x_{3}=1,$$
$$x_{2}=0,$$
$$x_{1}=-1.$$

__4.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

Матрица коэффициентов имеет вид

$$\begin{pmatrix}
81 & -45 & 45 \\ 
-45 & 50 & -15\\ 
45 & -15 & 38
\end{pmatrix}.$$

In [2]:
import numpy as np

In [3]:
a = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]
Определитель:
18225
Собственные значения:
[134.72475295   4.55103023  29.72421681]
Собственные векторы:
[[ 0.76360931 -0.62869675  0.14710953]
 [-0.48169913 -0.40297852  0.77818652]
 [ 0.42996136  0.66509301  0.61056083]]


Так как матрица коэффициентов невырожденная, симметричная и положительно определенная, то можно применить метод Холецкого.

Произведем разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=\sqrt{81}=9,$$
$$l_{21}=\frac{a_{21}}{l_{11}}=-\frac{45}{9}=-5,$$
$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9}=5,$$

$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}=\sqrt{25}=5,$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}\left ( -15+5\cdot5 \right )=2,$$

$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=3.$$

Получили матрицу 

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$$

Решим систему $Ly=b:$

$$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$$

$$y_{1} = 59,$$

$$y_{2} = -33,$$

$$y_{3} = -12.$$

И решим систему $L^{T}x=y:$

$$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=-12.
\end{cases}$$

$$x_{3} = -4,$$

$$x_{2} = -5,$$

$$x_{1} = 6.$$